Robert
awaz-ppg/office-pathfinder pull request #10
Opened 2019-04-27 17:02 UTC by robij1996

Poprawiłem niektóre rzeczy, choć jest parę których nie potrafię zrobić plus dodałem wyświetlanie konkretnego elementu.

2019-04-27 21:07 UTC, wazadrian requested changes

2019-04-27 21:07 UTC, wazadrian commented on .angulardoc.json
> +}
Do usunięcia

2019-04-27 21:07 UTC, wazadrian commented on .vs/ProjectSettings.json
> +}
Z tego co widzę to folder `.vs` do usunięcia

2019-04-27 21:07 UTC, wazadrian commented on frontend/.gitignore
> +/.vs
ten .gitignore niełapie tego folderu bo jest `.vs` jest poziom wyżej

2019-04-27 21:07 UTC, wazadrian commented on frontend/src/app/detail/detail.component.html
> +<div [ngClass] = "windowButton()"></div>
Żeby to zrobić dobrze musisz zmienić podejście. Wyśle rysunek
PS. [ngClass] służy do stylowania

Tu masz schemat dlaczego Ci  to działa
[https://drive.google.com/file/d/1ceSfK6nN35rPy1OykcJe4GbJlXat9IdS/view?usp=sharing](https://drive.google.com/file/d/1ceSfK6nN35rPy1OykcJe4GbJlXat9IdS/view?usp=sharing)

Postaraj się zrobić to prościej, jeżeli Ci ciężko to postaraj się to rozrysować i mi podeślij. Jestem pewny, że znasz wszystkie potrzebne rzeczy (były one używane w prototypach)

I postaraj się ograniczyć jak dużo component musi "wiedzieć" o reszcie aplikacji.

2019-04-27 21:07 UTC, wazadrian commented on frontend/src/app/detail/detail.component.html
> +    <mat-list-item class = "mat-background" *ngFor="let t of obj.tab">
Potrzebujesz modelu do wyświetlenia linii
``` ts
export class DetailList {
  public constructor(public label: string, public data: string) {}
}
```
i w zamiast interface'ów do modeli np `office.model.ts` robisz sobie klasę z metodą, która zmapuje na ten model

2019-04-27 21:07 UTC, wazadrian commented on frontend/src/app/detail/detail.component.html
> +<div *ngIf="close">
Powinno być `open`

2019-04-27 21:07 UTC, wazadrian commented on frontend/src/app/detail/detail.component.ts
> +    this.RoomService.isCliked = false;
to musi być zmienione

2019-04-27 21:07 UTC, wazadrian commented on frontend/src/app/model/viewModel.model.ts
> +export class ViewDesk {
to nie jest dobry pomysł z tą klasą

2019-04-28 08:49 UTC, awaz-ppg requested changes
Wrzuciłem ze złego konta komentarze.

2019-04-28 12:06 UTC, robij1996 commented on frontend/src/app/detail/detail.component.html
> +<div [ngClass] = "windowButton()"></div>
Jakich prototypach bo dalej tego nie widzę?

2019-05-07 08:11 UTC, closed without merging