Ksiwek/login
awaz-ppg/office-pathfinder pull request #20
Opened 2019-06-16 15:50 UTC by janex-PL

Zrobiłem logowanie i przekierowanie do panelu admina, w środku panela lista gości.

2019-06-16 19:32 UTC, awaz-ppg requested changes

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/admin/admin.component.html
> +    <h2 class="mat-h2">Guest List</h2>
Ta lista powinna być jako komponent będący dzieckiem admina, wtedy też łatwiej będzie można zrobić kolejne widoki

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/admin/admin.component.ts
> +    let token = localStorage.getItem('jwt');
niewykorzystany token

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/admin/admin.component.ts
> +    this.http.get<Guest[]>(`${environment.apiUrl}Guests`)
tutaj powinien być wykorzystany serwis `guest.service.ts`

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/admin/admin.component.ts
> +  logOut() {
dobrze by było logikę wylogowania trzymać w serwisie do autoryzacji

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/login/login.component.ts
> +    let token = localStorage.getItem('jwt');
metodę czy ktoś jest zalogowany też dobrze wyrzucić do serwisu z autoryzacją

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/login/login.component.ts
> +    const credentials = JSON.stringify(form.value);
zastanawiam się w jakim przypadku trzeba zrobić `json.stringify`, bo bez tego też będzie działać, jakbyś mógł podać przykład, bo jestem ciekawy

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/login/login.component.ts
> +    this.http.post(`${environment.apiUrl}Authorize`, credentials, {
to powinno wylecieć do serwisu z metodami korzystającymi z `HttpClient`a dla autoryzacji

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/login/login.component.ts
> +      const token = (response as any).token;
tutaj potrzebny jest model do odebrania tokena, ogólnie w `typescript` zawsze tworzy się modele, żeby mieć pewność co  miało w danym miejscu się pojawić

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/login/login.component.ts
> +      localStorage.setItem('jwt', token);
metoda do zalogowania, też powinna trafić do serwisu `authorize`

2019-06-16 19:32 UTC, awaz-ppg commented on frontend/src/app/auth.guard.ts
> +    let token = localStorage.getItem('jwt');
to czy użytkownik jest zalogowany wydziel do serwisu, a w guardzie sprawdź tylko co serwis zwróci

2019-06-17 00:54 UTC, janex-PL commented on frontend/src/app/login/login.component.ts
> +    const credentials = JSON.stringify(form.value);
Brałem fragment z tutoriala, dam wersję bez tego.

2019-06-17 07:48 UTC, awaz-ppg approved these changes
Ok teraz jest dobrze, ale trochę biedny ten panel admina ;p

2019-06-17 09:32 UTC, merged